# Generated by Django 2.1 on 2018-08-28 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180828_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 2, 49, 34, 316924, tzinfo=utc)),
        ),
    ]
